config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth' }
 
  root 'posts#index'
  get 'posts/new' => 'posts#new'
  post 'posts/new' => 'posts#create'
  get 'states' => 'users#states'
  get 'cities' => 'users#city'
  get 'destroy' => 'users#destroy'
  get 'activate/:id' => 'users#activate', as: 'activate'
  get 'index' => 'users#index'
  get 'user_profile/:id' => 'users#show', as: 'user_profile'
  
  post 'draft' => 'posts#draft'
  get 'draft' => 'posts#draft_show'
  resources :posts
  resources :users do 
    collection do 
      get 'myprofile'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable,
         :omniauthable, omniauth_providers: [ :github, :google_oauth2 ]
  
  has_many :posts, dependent: :destroy

  enum status: {active:0, inactive:1}

  mount_uploader :photos, PhotosUploader

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
      user.name = provider_data.info.name
      user.phone_no = provider_data.info.contact
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.skip_confirmation!
      end
  end

  # app/models/user.rb  
  
  # instead of deleting, indicate the user requested a delete & timestamp it  
  def soft_delete  
    update_attribute(:deleted_at, Time.current)  
  end  
  
  # ensure user account is active  
  def active_for_authentication?  
    super && !deleted_at  
  end  
  
  # provide a custom message for a deleted account   
  def inactive_message   
    !deleted_at ? super : :deleted_account  
  end  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/omniauth_controller.rb
class Users::OmniauthController < ApplicationController

# github callback
def github
	# debugger
  @user = User.create_from_provider_data(request.env['omniauth.auth'])
  if @user.persisted?
    # debugger
    sign_in_and_redirect @user
    # set_flash_message(:notice, :success, kind: 'GitHub') if is_navigational_format?
  else
    flash[:error] = 'There was a problem signing you in through GitHub. Please register or try signing in later.'
    redirect_to new_user_registration_url
  end
end

# google callback
def google_oauth2
  @user = User.create_from_provider_data(request.env['omniauth.auth'])
  if @user.persisted?
    sign_in_and_redirect @user
    # set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
  else
    flash[:error] = 'There was a problem signing you in through Google. Please register or try signing in later.'
    redirect_to new_user_registration_url
  end
end


def failure
  flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
  redirect_to new_user_registration_url
end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   resource.soft_delete
  #   Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
  #   set_flash_message :notice, :destroyed
  #   yield resource if block_given?
  #   respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  # end

  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    # debugger
    if (User.find_by(email: "#{params[:user][:email]}").status == 'active')
      super
    else
     redirect_to new_user_registration_path 
    end

  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class	UsersController <ApplicationController
	

	def index
		@users = User.all.order(:name)
	end

	def show
		@user = User.find(params[:id])
	end


	# def myprofile
	# 	@user = User.find_by(id: current_user)
	# end

	# def destroy
	# 	if (user_signed_in? && current_user.is_admin);
	# 	 	@user = User.find(params[:id])
 #    	@user.update(status:'inactive')
 #    else 
 #     	@user = User.find(current_user[:id])
 #    	@user.update(status:'inactive')
 #    	redirect_to destroy_user_session_path
 #   	end
 #  end

 #  def activate
	# 	 	@user = User.find(params[:id])
 #    	@user.update(status:'active')
 #    	# debugger

 #    	redirect_to user_profile_path
 #  end


 #  def states
 #  	@country_key = CS.countries.key("#{params[:country]}")
 #  	@states = CS.states(@country_key)
 #  	# debugger
 #  end

 #  def city
 #  	@country_key = CS.countries.key("#{params[:country]}")
 #  	@state_key = CS.states(@country_key).key("#{params[:state]}")
 #  	@cities = CS.get(@country_key, @state_key)
  	
  end
	private 
		def params
			params.require(:post).permit(:title, :description, :post)
		end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users/omniauth_helper.rb
module Users::OmniauthHelper
end

app/views/users/city.js.erb
var city = document.getElementById("user_city");
// Clear the options in the select box
while (city.firstChild) city.removeChild(city.firstChild);
// Add a placeholder
var placeholder = document.createElement("option");
placeholder.text = "Choose a city";
placeholder.value = "";
city.appendChild(placeholder);
// Add the states
<% @cities.each do |c| %>
    city.options[city.options.length] = new Option('<%= c %>');
<% end %>

app/views/users/index.html.erb
<h1 class="d-flex justify-content-center align-content-center">users</h1><br>
<table class="d-flex justify-content-around border-1 m-5">
		
		<tr class="border-dark">
				<th class="border-2 p-2 text-center"><b>Id</th>
				<th class="border-2 p-2 text-center"><b>Name</th>
				<th class="border-2 p-2 text-center"><b>Status</th>
				<th class="border-2 p-2 text-center" colspan="3">Operations</th>
		</tr>		
		
			<% @users.each do |user|%>
					<tr>
						<td class="border-1 p-2"><%= user.id %></td>
						<td class="border-1 p-2"><%= user.name %></td>
						<td class="border-1 p-2"><%= user.status %></td>
						<td class="border-1 p-2">
						
						<%= button_to 'Activate',  activate_path(id: user.id),class:"btn-secondary rounded", method: :get %>
						<%= button_to 'Deactivate',  user_path(user.id), method: :delete, class:'delete-btn btn-secondary rounded' %>
						<%= button_to 'Show',  user_profile_path(user.id), method: :get, class:"btn-secondary rounded"%>

						</td>
					</tr>
			<% end %>

</table>

<script>
	// $(document).ready(() => {

	// 	$('.delete-btn').click((e) => { deleteConfirmation(e) })
	    
	  var deleteButton = document.querySelectorAll(".delete-btn");
	  for (var i = 0; i < deleteButton.length; i++){
		  	deleteButton[i].addEventListener("click", deleteConfirmation);
	  	}
	  		function deleteConfirmation(e) {
		    	console.log('FUNC');
		    	if (confirm("Are you sure?")) {
		    	console.log('Delete');
		    	}
		    	else {
		    	console.log('DONT DELETE');
		      event.preventDefault()
		    	}
		  
		  	}
	    
	// })
</script>

app/views/users/myprofile.html.erb
	<div class="d-flex justify-content-center border-1 "><h1>User Details</h1></div><br>
	

	<div class="d-flex justify-content-center border-1 ">
				   <%= image_tag(@user.photos.url) if @user.photos.url %>
	</div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Id :</b> <%= @user.id %> </div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Name : </b><%= @user.name %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Contact : </b><%= @user.phone_no %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Age : </b><%= @user.age %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Country : </b><%= @user.country %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>State : </b><%= @user.state %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>City : </b><%= @user.city %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Email : </b><%= @user.email %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Gender : </b><%= @user.gender %></div><br>

	<div class="d-flex justify-content-center border-1"><%= link_to "Back", :back, class:"btn btn-secondary" %></div>
	

app/views/users/show.html.erb
<div class="d-flex justify-content-center border-1 "><h1>User Details</h1></div><br>
	

	<div class="d-flex justify-content-center border-1 ">
				   <%= image_tag(@user.photos.url) if @user.photos.url %>
	</div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Id :</b> <%= @user.id %> </div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Name : </b><%= @user.name %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Contact : </b><%= @user.phone_no %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Age : </b><%= @user.age %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Country : </b><%= @user.country %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>State : </b><%= @user.state %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>City : </b><%= @user.city %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Email : </b><%= @user.email %></div>
	<div class="d-flex justify-content-center border-1 m-1"><b>Gender : </b><%= @user.gender %></div><br>

	<div class="d-flex justify-content-center border-1"><%= link_to "Back", :back, class:"btn btn-secondary" %></div>

app/views/users/states.js.erb
var state = document.getElementById("user_state");
// Clear any populated options in the select box
while (state.firstChild) state.removeChild(state.firstChild);
// Add a placeholder
var placeholder = document.createElement("option");
placeholder.text = "Choose a state";
placeholder.value = "";
state.appendChild(placeholder);
// Use erb templating to add the states
<% @states.each do |s| %>
  state.options[state.options.length] = new Option('<%= s[1] %>', '<%= s[1] %>')
<% end %>