config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth' }
 
  root 'posts#index'
  get 'posts/new' => 'posts#new'
  post 'posts/new' => 'posts#create'
  get 'states' => 'users#states'
  get 'cities' => 'users#city'
  get 'destroy' => 'users#destroy'
  get 'activate/:id' => 'users#activate', as: 'activate'
  get 'index' => 'users#index'
  get 'user_profile/:id' => 'users#show', as: 'user_profile'
  
  post 'draft' => 'posts#draft'
  get 'draft' => 'posts#draft_show'
  resources :posts
  resources :users do 
    collection do 
      get 'myprofile'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <div class="container-fluid">
        <%= link_to 'Posts', posts_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Add Post', posts_new_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Draft Post', draft_path, class:"nav-link"%>
        </li>
        <div class="d-flex ">
          <li class="nav-item">
          <%= link_to 'Sign Out',destroy_user_session_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'My Profile', myprofile_users_path, class:"nav-link"%>
        </li>
        </div>

          <% if user_signed_in? && current_user.is_admin %>
            <li class="nav-item">
              <%= link_to 'Users', users_path, class:"nav-link"%>
            </li>
          <% end %>

      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>
      <% end %>
      </ul>
      
      <div class="float-right">
        <%= form_with url: root_path,  model: @post, method: :get do |form| %>
        <%= form.text_field :title, id:"search-title" %>
        <%= form.submit :search, class:"btn-secondary rounded" %>
        <% end %>
      </div>

    </div>
  </div>
</nav>