config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth' }
 
  root 'posts#index'
  get 'posts/new' => 'posts#new'
  post 'posts/new' => 'posts#create'
  get 'states' => 'users#states'
  get 'cities' => 'users#city'
  get 'destroy' => 'users#destroy'
  get 'activate/:id' => 'users#activate', as: 'activate'
  get 'index' => 'users#index'
  get 'user_profile/:id' => 'users#show', as: 'user_profile'
  
  post 'draft' => 'posts#draft'
  get 'draft' => 'posts#draft_show'
  resources :posts
  resources :users do 
    collection do 
      get 'myprofile'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
    validates :title, format: { with: /\A[a-zA-Z\s]+\z/ }, presence:true
    validates :description, length: {minimum: 30 }, presence:true 
  

  enum draft: { draft: 0, show: 1 }
  

  mount_uploader :post, PostUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!, only:[:edit, :new, :destroy]
  skip_before_action :verify_authenticity_token
  def index
    if params[:title]
  	@posts = Post.where("title ilike ?", "%#{params[:title]}%")
    else
    @posts = Post.all.order(:id)
    end
  end

  def edit
  	@action = 'edit'
  	@post = Post.find(params[:id])

  end

  def update
  	@post = Post.find(params[:id])
  	
  	if @post.update(posts_params) 
  		redirect_to root_path, notice: "Post is Updated Successfully"
  	else
  		render 'edit'
  	end

  end

  def new
  	@action = 'new'
  	@post = Post.new
  end

  def create
  	debugger
    @post = current_user.posts.new(posts_params)
  	is_validate = (posts_params[:draft] == 'draft')

    if @post.save( validate: !is_validate )
      # @post.update(draft: 'show')
  		# PostMail.new(@post).send_mail 		
  		redirect_to root_path, notice: "Post is Created Successfully"  
  	end
    # end
  end

  def show
  	@post = Post.find(params[:id])
  end

  	def destroy
  	@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path, notice: "Post is Deleted Successfully"
 	  end

    def draft_show
      @post = Post.all.order(:id).where(draft: 'draft')

    end

    def draft
      @post = current_user.posts.new(posts_params)
      @post.save!
      @post.update(draft: 'draft')
      redirect_to draft_path, notice: "Post is saved as draft Successfully"  
    end
	private 
		def posts_params
			params.require(:post).permit(:title, :description, :post, :draft)
		end

end

app/helpers/posts_helper.rb
module PostsHelper
	def user_name(post)
		post.present? ? "#{(post.user.name).capitalize!}" : '' 
	end

end

app/views/posts/_alert.html.erb
<div class="alert alert-info alert-dismissible  show text-center" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/posts/_form.html.erb
<section class="d-block m-auto d-flex justify-content-center">
<%= form_with model: @post, url: @action == 'edit' ?   post_path : posts_new_path, method: @action=='edit' ? :patch : :post , id:'form'  do |form| %>
    <div class="m-4">
        

        <%= form.label :title, "Title :"%><br>
        <%= form.text_field :title , class:'input form-control', id: "post_title"%><br>
        
        <%= form.label :description , "Description :"%><br>
        <%= form.text_area :description , size: 100*5, class:'input form-control' %><br>

        <%= form.label :post, "Upload File :"%><br>
        <%= form.file_field :post , class:'form-control'%><br>

        <div class="d-flex justify-content-center m-3">
            <%= link_to "Back", :back, class:"btn btn-secondary m-3" %>
            <input type="button" class="btn-secondary btn draft m-3" value="Save as Draft" id="draft"></input><br>
            <input type="button" class="btn-secondary btn submit m-3" value="Submit" id="btn"></input><br>
        </div>
    </div>
</section>
<%end%>

<%= javascript_include_tag 'post_draft' %>
<%= javascript_include_tag 'post_submit' %>

app/views/posts/draft_show.html.erb
<h1 class="d-flex justify-content-center align-content-center">Draft Posts</h1><br>
<table class="d-flex justify-content-around border-1 m-5">
		
		<tr class="border-dark">
				<th class="border-2 p-2 text-center"><b>Id</th>
				<th class="border-2 p-2 text-center"><b>User</th>
				<th class="border-2 p-2 text-center"><b>Title</th>
				<th class="border-2 p-2 text-center"><b>Description</th>
			
					<th class="border-2 p-2 text-center" colspan="3">Operations</th>
		</tr>		
		
			<% @post.each do |post|%>
				<% if ((user_signed_in?) && (post.user.name == current_user.name)) %>
					<tr>
						<td class="border-1 p-2"><%= post.id %></td>
						<td class="border-1 p-2"><%= post.user.name %></td>
						<td class="border-1 p-2"><%= post.title %></td>
						<td class="border-1 p-2"><%= post.description %></td>
							<td class="border-1 p-2">
=							<%= button_to 'Edit',  edit_post_path(post),class:"btn-secondary rounded", method: :get %>
							<%= button_to 'Destroy',  post_path(post), method: :delete, class:'delete-btn btn-secondary rounded' %>
							</td>
					</tr>
				<%end%>
			<%end%>

</table>

app/views/posts/edit.html.erb
<h1 class="d-block m-auto d-flex justify-content-center">Edit post</h1>
<%= render 'form'%>

app/views/posts/index.html.erb
<h1 class="d-flex justify-content-center align-content-center">Posts</h1><br>
<table class="d-flex justify-content-around border-1 m-5">
		
		<tr class="border-dark">
				<th class="border-2 p-2 text-center"><b>Id</th>
				<th class="border-2 p-2 text-center"><b>User</th>
				<th class="border-2 p-2 text-center"><b>Title</th>
				<th class="border-2 p-2 text-center"><b>Description</th>
			
				<% if user_signed_in? %>
					<th class="border-2 p-2 text-center" colspan="3">Operations</th>
				<%end%>
		</tr>		
		
			<% @posts.each do |post|%>
					<tr>
						<% if !(post.draft == 'draft') %>
						<td class="border-1 p-2"><%= post.id %></td>
						<td class="border-1 p-2"><%= post.user.name %></td>
						<td class="border-1 p-2"><%= post.title %></td>
						<td class="border-1 p-2"><%= post.description %></td>
							<% if user_signed_in? %>
							<td class="border-1 p-2">
							<% if post.user.name == current_user.name %>
							<%= button_to 'Edit',  edit_post_path(post),class:"btn-secondary rounded", method: :get %>
							<%= button_to 'Destroy',  post_path(post), method: :delete, class:'delete-btn btn-secondary rounded' %>
							<% end %>
							<%= button_to 'Show',  post_path(post), method: :get, class:"btn-secondary rounded"%>
							</td>
							<% end %>
					</tr>
					<% end %>
			<%end%>

</table>


<br>
<br>
<div class=" d-flex justify-content-around">
<button class="p-2 btn-primary btn  rounded-2 p-2"><a class="text-decoration-none text-light" href="posts/new"> Create Posts</a></button>
</div>
<script>
	// $(document).ready(() => {

	// 	$('.delete-btn').click((e) => { deleteConfirmation(e) })
	    
	  var deleteButton = document.querySelectorAll(".delete-btn");
	  for (var i = 0; i < deleteButton.length; i++){
		  	deleteButton[i].addEventListener("click", deleteConfirmation);
	  	}
	  		function deleteConfirmation(e) {
		    	console.log('FUNC');
		    	if (confirm("Are you sure?")) {
		    	console.log('Delete');
		    	}
		    	else {
		    	console.log('DONT DELETE');
		      event.preventDefault()
		    	}
		  
		  	}
	    
	// })
</script>

<!-- <script type="text/javascript">
$(function() {
  $('#showall').click(function() {
    $('.targetDiv').show();
  });
  $('.showSingle').click(function() {
    $('.targetDiv').hide();
    $('#div' + $(this).attr('target')).show();
  });
});
</script>
<div class="buttons">
  <a id="showall">All</a>
  <a class="showSingle" target="1">Div 1</a>
  <a class="showSingle" target="2">Div 2</a>
  <a class="showSingle" target="3">Div 3</a>
  <a class="showSingle" target="4">Div 4</a>
</div>
<div id="div1" class="targetDiv">Lorum Ipsum1</div>
<div id="div2" class="targetDiv">Lorum Ipsum2</div>
<div id="div3" class="targetDiv">Lorum Ipsum3</div>
<div id="div4" class="targetDiv">Lorum Ipsum4</div> -->

app/views/posts/new.html.erb
<h1 class="d-block m-auto d-flex justify-content-center">Enter post details</h1>
<%= render 'form'%>

app/views/posts/show.html.erb
<h1 class="d-block m-auto d-flex justify-content-center"><u>
	<%= @post.title%></u>		
	</h1>
<br>
<div class="d-block m-auto d-flex justify-content-center">
	<h3>
		Description
	</h3>
</div>
<div class="d-block m-5 d-flex justify-content-center">
 <%= @post.description %><br><br>
</div>

<div class="d-block m-auto d-flex justify-content-center">
  <p>
    <label class="d-block m-auto d-flex justify-content-center"></label><br>
    <%= image_tag(@post.post.url) if @post.post.url %>
  </p>
</div>
<%= link_to "Back", :back, class:" m-5 btn btn-secondary m-3" %>

<% if @post.user.name == current_user.name %>
<div class="d-block m-auto d-flex justify-content-center">
<div class="m-2">	<%= button_to "Go to Home", posts_path , method: :get, class:"m-2 btn-secondary rounded-2" %>
</div>
<div class="m-2 ">	<%= button_to "Edit", edit_post_path, method: :get, class:"m-2 btn-secondary rounded-2" %>
</div>
<div class="m-2">	<%= button_to 'Destroy',  post_path(@post), method: :delete, class:"m-2 btn-secondary rounded-2", id:'delete-btn' %>
</div>
</div>
<% end %>
<script>
  deleteButton = document.querySelector("#delete-btn");
  deleteButton.addEventListener("click", deleteConfirmation);
  function deleteConfirmation(e) {
    if (confirm("Are you sure?")) {
      
    }else {
      event.preventDefault()
    }
  }
</script>
 